run: cat date ls mkdir rm shell

cat: cat.c
	gcc cat.c -o cat

date: date.c
	gcc date.c -o date

ls: ls.c
	gcc ls.c -o ls

mkdir: mkdir.c
	gcc mkdir.c -o mkdir

rm: rm.c
	gcc rm.c -o rm

shell: shell.c
	gcc shell.c -o shell -lpthread

clean:
	rm -f run cat date ls mkdir rm shell